### ISSUE TITLE
How to handle attributes that needs to be included with an empty string?

### ISSUE THREAD

**Issue by dkulchinsky** [terraform-kops/terraform-provider-kops#68]
Hey folks 👋🏼 

This is a follow-up on #46, I was able to swap the gossip protocols and it worked as expected.

Now, I'm trying to disable the secondary protocol, for this the generated kops config should look like this:
```yaml
  gossipConfig:
    protocol: memberlist
    listen: 0.0.0.0:4000
    secondary:
      protocol: ""

  dnsControllerGossipConfig:
    protocol: memberlist
    listen: 0.0.0.0:3993
    seed: 127.0.0.1:4000
    secondary:
      protocol: ""
```

notice the `secondary` empty string value for the `protocol` key.

with the current provider code, if I set the config to this:
```hcl
  gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:4000"
    secondary {
      protocol = ""
    }
  }

  dns_controller_gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:3993"
    seed     = "127.0.0.1:4000"
    secondary {
      protocol = ""
    }
  }
```

The terraform plan diff looks correct:
![image](https://github.com/terraform-kops/terraform-provider-kops/assets/61992380/afb7d434-5ae8-43c0-81f0-9128ec4c977b)

However, the produced kops config is rendered with an empty `secondary` block:
```yaml
  dnsControllerGossipConfig:
    listen: 0.0.0.0:3993
    protocol: memberlist
    secondary: {}
    seed: 127.0.0.1:4000

  gossipConfig:
    listen: 0.0.0.0:4000
    protocol: memberlist
    secondary: {}
```

while I was expecting:
```yaml
  dnsControllerGossipConfig:
    listen: 0.0.0.0:3993
    protocol: memberlist
    secondary:
      protocol: ""
    seed: 127.0.0.1:4000

  gossipConfig:
    listen: 0.0.0.0:4000
    protocol: memberlist
    secondary:
      protocol: ""
```

Any suggestion on how to handle this case?

**Comment by eddycharly** [comment]
@dkulchinsky does it changes something ? what is the go type for `protocol` ?

**Comment by eddycharly** [comment]
IIRC that's why i created the `nullable` helper. Can you try with:
```
generate(kops.GossipConfigSecondary{},
  nullable("Protocol"),
),
generate(kops.DNSControllerGossipConfigSecondary{},
  nullable("Protocol"),
),
```

**Comment by dkulchinsky** [comment]
> IIRC that's why i created the `nullable` helper. Can you try with:
> 
> ```
> generate(kops.GossipConfigSecondary{},
>   nullable("Protocol"),
> ),
> generate(kops.DNSControllerGossipConfigSecondary{},
>   nullable("Protocol"),
> ),
> ```

ohh!! that looks promising 👍🏼 

I'll give it a go 🤞🏼

**Comment by dkulchinsky** [comment]
@eddycharly so I'm testing this out with the change in #70 

now the produced kops config is:
```yaml
  dnsControllerGossipConfig:
    listen: 0.0.0.0:3993
    protocol: memberlist
    secondary:
      protocol: "false"
    seed: 127.0.0.1:4000

  gossipConfig:
    listen: 0.0.0.0:4000
    protocol: memberlist
    secondary:
      protocol: "false"
```

The terraform code I used:
```hcl
  gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:4000"
    secondary {
      protocol {
        value = false
      }
    }
  }

  dns_controller_gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:3993"
    seed     = "127.0.0.1:4000"
    secondary {
      protocol {
        value = false
      }
    }
  }
```

**Comment by dkulchinsky** [comment]
> @dkulchinsky does it changes something ? what is the go type for `protocol` ?

it's a string

https://github.com/kubernetes/kops/blob/fc910854e5c5a4a78e14e173dc523ed4c2f70f80/pkg/apis/kops/cluster.go#L991

https://github.com/kubernetes/kops/blob/fc910854e5c5a4a78e14e173dc523ed4c2f70f80/pkg/apis/kops/cluster.go#L1005

**Comment by eddycharly** [comment]
@dkulchinsky nope, it's a string pointer ;-)

**Comment by eddycharly** [comment]
The tf config should be something like this:

```
  gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:4000"
    secondary {
      protocol {
        value = ""
      }
    }
  }
```

**Comment by eddycharly** [comment]
To highlight the difference with `nullable` you can now do:
---
```hcl
  gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:4000"
    secondary {
      protocol {
        value = ""
      }
    }
  }
```
Should produce:
```yaml
  gossipConfig:
    listen: 0.0.0.0:4000
    protocol: memberlist
    secondary:
      protocol: ""
```
---
```hcl
  gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:4000"
    secondary {}
  }
```
Should produce:
```yaml
  gossipConfig:
    listen: 0.0.0.0:4000
    protocol: memberlist
    secondary: {}
```
---
That is, we can differentiate an value that is not set at all from a default values (which is not possible natively in a plugin).

**Comment by dkulchinsky** [comment]
@eddycharly thank you! this makes total sense!

and of course, it's a string pointer 🤦🏼‍♂️ 

will report back once I had a chance to test it out as suggested.

**Comment by dkulchinsky** [comment]
@eddycharly thanks again for your help! can confirm with `value = ""` the correct kops config is now produced!

```hcl
  gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:4000"
    secondary {
      protocol {
        value = ""
      }
    }
  }

  dns_controller_gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:3993"
    seed     = "127.0.0.1:4000"
    secondary {
      protocol {
        value = ""
      }
    }
  }
```

produces:
```yaml
  dnsControllerGossipConfig:
    listen: 0.0.0.0:3993
    protocol: memberlist
    secondary:
      protocol: ""
    seed: 127.0.0.1:4000

  gossipConfig:
    listen: 0.0.0.0:4000
    protocol: memberlist
    secondary:
      protocol: ""
```
